"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.render_readme = render_readme;
function content() {
    return `
# WebSocket Client
generated by [async-rust-ws-template](https://github.com/kanekoshoyu/asyncapi-rust-ws-template)
  `;
}
function render_readme() {
    return React.createElement(File, { name: "README.md" },
        " ",
        content(),
        " ");
}
