import { render } from './tool';

function content() {
  return `
# WebSocket Client
generated by [async-rust-ws-template](https://github.com/kanekoshoyu/asyncapi-rust-ws-template)
  `;
}

export function render_readme() {
  return render("README.md", content());
}
