import { RenderFile } from './renderFile';
import { AsyncAPIDocumentInterface } from '@asyncapi/parser';

function contentModule(nameModule: string, description: string): String {
  return `/// ${description}
mod ${nameModule};
`
}

function content(): string {
  let defineMod: string = "";
  let contents = [contentModule("client", "client code"), contentModule("model", "model code (generated by modelina)")];

  for (const content of contents) {
    defineMod += content;

  }
  return defineMod;
}

export function renderLibRs(doc: AsyncAPIDocumentInterface): RenderFile {
  return new RenderFile("src/lib.rs", content());

}
