import { RenderFile } from './renderFile';

function contentModule(nameModule: string, description: string): string {
	return `
/// ${description}
pub mod ${nameModule};
`.trimStart()
}

function content(): string {
	let defineMod: string = "";
	const contents = [contentModule("client", "client code"), contentModule("model", "model code (generated by modelina)")];

	for (const content of contents) {
		defineMod += content;

	}
	return defineMod;
}

export function renderLibRs(): RenderFile {
	return new RenderFile("src/lib.rs", content());

}
